name: "Neville Bethel"
description: "The Personal Homepage for Neville Bethel"

url: "http://nevillebethel.com"

paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: pygments
markdown: kramdown
kramdown: 
  parse_block_html: true